### PR TITLE
Allow zero tolerance, but issue a warning.

### PR DESCRIPTION
**Pull request by hendriks73**
Change as discussed in #300, i.e. following @stefan-balke 's suggestions to allow a tolerance of zero, but issue a warning.

### CODE REVIEW

**Comment by craffel** [comment]
Hey Hendrik, Travis is passing again. This looks good but I think you will have to include a check for the warning in your test. Do you want to add that? That will also retrigger Travis :)

**Comment by hendriks73** [comment]
Lines too long... gee...

**Comment by craffel** [comment]
Merged, thanks!

**Comment by hendriks73** [comment]
Thank you!

**Pull request merged**
