### PR TITLE
Tempo improvement

### PR DESCRIPTION
**Pull request by bmcfee**
Fixes outstanding issues wrt tempo detection:

- #99 
- #123
- #124 
- #128

### CODE REVIEW

**Comment by bmcfee** [comment]
Still to-do: correctness and validation tests.

**Comment by craffel** [comment]
Sweet, yes, let's get the tempo.py coverage up to 100% while you're at it.

**Comment by bmcfee** [comment]
> let's get the tempo.py coverage up to 100%

done.

**Comment by craffel** [comment]
Woo!  Merged.

**Pull request merged**
