### PR TITLE
changed positional argument name in filter_kwargs

### LINKED ISSUE #165: filter_kwargs parameter name collision
I'm trying to use `util.filter_kwargs` on sonify functions, and hitting a collision with the argument `function`.

This would be fixed by renaming `filter_kwargs`'s `function` argument (not a keyword argument) to something unique, like `wrapped_function`.

This should be a trivial change, and I can PR if it sounds reasonable.

### PR DESCRIPTION
**Pull request by bmcfee**
Fixes #165

### CODE REVIEW

**Comment by craffel** [comment]
Will merge when Travis passes.

**Comment by bmcfee** [comment]
We're getting a lot of travis failures due to timeouts.  Hopefully this is a temporary situation.

**Comment by craffel** [comment]
Please rebase.

**Comment by craffel** [comment]
LGTM, merging, thanks!

**Pull request merged**
