### PR TITLE
[WIP] adds changelog to documentation

### PR DESCRIPTION
**Pull request by bmcfee**
implements #184

### CODE REVIEW

**Comment by craffel** [comment]
What's the current status?  Anything I can help out with?

**Comment by bmcfee** [comment]
I think it's up to date.

**Comment by bmcfee** [comment]
... near as I can tell, the changelog covers all of the major issues for each release now.  I skipped over some of the minor ones that only affect things between versions.  For example, frame-wise bss didn't exist in 0.3, so I added an entry for the corresponding initial PR, but not for any of the subsequent patches prior to 0.4.

If that seems reasonable, I think we can merge and :shipit:

**Comment by craffel** [comment]
Merged, thanks!

**Pull request merged**
